version: '3'
services:
  web:
    build: .
    command: foreman start
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis