:verbose: true
:pidfile: ./pid/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 10
:queues:
    - hard_worker

:schedule:
  DashboardKudosWorker:
    cron: '*/5 * * * *'   # Runs once every 5 min
    class: DashboardKudosWorker